### ISSUE TITLE
可以支持横屏吗？或者根据重力感应器来自动判断

### ISSUE THREAD

**Issue by TwoIceBing** [ckcz123/H5mota-Android#2]
目前应该是写死了只允许竖屏，所以用手机玩mota50层时界面太小了。
![portrait](https://github.com/ckcz123/H5mota-Android/assets/33338766/ed2bcf33-abe6-4130-b930-fd3c10c5db57)

android:screenOrientation属性。他有下面几个參数：

- “unspecified”:默认值 由系统来推断显示方向.判定的策略是和设备相关的，所以不同的设备会有不同的显示方向。
- “landscape”:横屏显示（宽比高要长）
- “portrait”:竖屏显示(高比宽要长)
- “user”:用户当前首选的方向
- “behind”:和该Activity以下的那个Activity的方向一致(在Activity堆栈中的)
- “sensor”:有物理的感应器来决定。假设用户旋转设备这屏幕会横竖屏切换。
- “nosensor”:忽略物理感应器。这样就不会随着用户旋转设备而更改了（"unspecified"设置除外）。

**Comment by ckcz123** [comment]
现在新版本已经支持了。
